name: Build and deploy PHP app to Superhosting

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
   PHP_VERSION: '8.x'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          destination: "./public_html"
          
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./public_html"
          remote_dir: "./public_html"

