name: Release and deploy to Superhosting
# This workflow is triggered when a new tag is published
# `git tag v0.0.1alpha`
# `git push --tags`
# If the tag already exists, use this commanf to delete it `git tag -d v0.0.1alpha`

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  release:
    if: contains(github.ref, 'tags/v')
    permissions: write-all
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      v_num:  ${{ steps.version.outputs.number }}


    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          destination: "./public_html"

      - name: Get version number
        id: version
        run: |
          echo "number=$(echo '${{ github.ref }}' | cut -d '/' -f 3)" >>${GITHUB_OUTPUT}

      - name: Show version number
        run: |
          echo ${{ steps.version.outputs.number }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: true    

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: takecontrolsoft${{ steps.version.outputs.number }}
          path: public_html

      - name: Upload Release Asset
        if: ${{ steps.create_release.outputs.upload_url != '' }}
        uses: glentiki/xbin-release-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          assets_path: "./public_html"
          assets_name: takecontrolsoft${{ steps.version.outputs.number }}
         
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./public_html"
          remote_dir: "./public_html"

        
                      
